FROM golang:1.15.7-alpine3.13

SHELL ["/bin/ash", "-c"]
WORKDIR /go/src/app
COPY ./app ./
EXPOSE 8080
ENV GO111MODULE=on
RUN go mod download
CMD ["export GO_ENV=/go/src/app"]

RUN apk add --no-cache alpine-sdk

# Hot Reload
RUN go get github.com/pilu/fresh

# libraries
RUN go get github.com/labstack/echo
RUN go get -v golang.org/x/tools/gopls

CMD ["fresh -c .fresh.conf"]